# testowanie wszystkich przyciskow

# -*- coding: utf-8 -*-

def main():
    startApplication("calqlatr")
    mouseClick(waitForObject(":0_Text"))
    mouseClick(waitForObject(":1_Text"))
    mouseClick(waitForObject(":2_Text"))
    mouseClick(waitForObject(":3_Text"))
    mouseClick(waitForObject(":window_Rectangle"), 224, 251, Qt.LeftButton)
    mouseClick(waitForObject(":4_Text_2"))
    test.vp("VP1")
    mouseClick(waitForObject(":C_Text"))
    mouseClick(waitForObject(":5_Text"))
    mouseClick(waitForObject(":6_Text"))
    mouseClick(waitForObject(":7_Text"))
    mouseClick(waitForObject(":8_Text_2"))
    mouseClick(waitForObject(":9_Text"))
    test.vp("VP2")
    mouseClick(waitForObject(":C_Text"))
    mouseClick(waitForObject(":1_Text"))
    mouseClick(waitForObject(":±_Text"))
    mouseClick(waitForObject(":−_Text"))
    mouseClick(waitForObject(":2_Text"))
    mouseClick(waitForObject(":=_Text"))
    test.vp("VP3")
    mouseClick(waitForObject(":C_Text"))
    mouseClick(waitForObject(":4_Text_2"))
    mouseClick(waitForObject(":+_Text"))
    mouseClick(waitForObject(":5_Text"))
    mouseClick(waitForObject(":÷_Text"))
    mouseClick(waitForObject(":2_Text"))
    mouseClick(waitForObject(":×_Text"))
    mouseClick(waitForObject(":6_Text"))
    mouseClick(waitForObject(":=_Text"))
    test.vp("VP4")
    mouseClick(waitForObject(":C_Text"))
    mouseClick(waitForObject(":6_Text"))
    mouseClick(waitForObject(":√_Text"))
    mouseClick(waitForObject(":+_Text"))
    mouseClick(waitForObject(":3_Text"))
    mouseClick(waitForObject(":._Text"))
    doubleClick(waitForObject(":window_Rectangle"), 229, 185, Qt.LeftButton)
    mouseClick(waitForObject(":5_Text"))
    mouseClick(waitForObject(":=_Text"))
    test.vp("VP5")
